name: Create GitHub Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-github-release:
    if: ${{ github.repository == 'alextheman231/alex-c-line' }}
    uses: alextheman231/github-actions/.github/workflows/create-github-release.yml@f00401c75c7e0e158a87be24c87ee8ebbd664dbb # v10.5.1
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
